### ISSUE TITLE
Make AlmaLinux and CloudLinux cloud-init changes upstream

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/cloud-init#1]
Build for test - https://build.almalinux.org/build/7118
Changes - https://git.almalinux.org/rpms/cloud-init/commit/67f196acec3cf4c7ce87794ec307b75474aa6974

**Comment by lkhn** [comment]
Fix AlmaLinux OS and CloudLinux OS support for NTP module: https://github.com/canonical/cloud-init/pull/5235

**Comment by lkhn** [comment]
Add AlmaLinux OS and CloudLinux OS support for CA Certificates modules: https://github.com/canonical/cloud-init/pull/5264

**Comment by lkhn** [comment]
Improve AlmaLinux OS and CloudLinux OS support on systemd services: https://github.com/canonical/cloud-init/pull/5265

**Comment by andrewlukoshko** [comment]
Done
